### PR TITLE
Added VaibhavSaini19's repos

### LINKED ISSUE #16: Add other repositories in the mix for collaboration
There are other projects that need to be included like [BootBlox](https://github.com/VaibhavSaini19/BootBlox) and many defunct repositories to be removed.

### PR DESCRIPTION
**Pull request by gridhead**
Removed some of t0xic0der's repos

Signed-off-by: t0xic0der <akashdeep.dhar@gmail.com>

### CODE REVIEW

**Review by s-katte — CHANGES_REQUESTED** [review]
Hey @t0xic0der, could you please move Astrosonic issues to the top and followed by other repositories alphabetically.

**Comment by gridhead** [comment]
I have made the changes requested. Take a look.

**Review by s-katte — APPROVED** [review]
Contribution appreciated @t0xic0der.
If you fee you got something good out of it, please feel free to leave a star ⭐ behind.

Happy hacking!

**Comment by gridhead** [comment]
@VaibhavSaini19 Please retain the changes made in this branch at the cost of replacing the existing ones at the master.

**Comment by gridhead** [comment]
Thanks for the conflict resolution. @s-katte do take a look.

**Pull request merged**
