### PR TITLE
Added modal for rate limit exceed

### LINKED ISSUE #3: Address the exception when user is beyond API rate limit
The possible solutions might be to catch such an occurrence and then show a modal to the user stating that they would not be able to use the site for sometime and need to come back later when their IP has gone below the limit.

### PR DESCRIPTION
**Pull request by s-katte**

### CODE REVIEW

**Review by gridhead — CHANGES_REQUESTED** [review]
Could you please restore the cross-site imports to one per line? Thank you.

**Comment by s-katte** [comment]
Sure! check it out

**Review by gridhead — COMMENTED** [review]
Hi @s-katte! Could you please attach images of how the modal is supposed to look once the API rate limit is exceeded from an IP? Also, what are the console outputs in those scenarios?

**Comment by s-katte** [comment]
Screenshot from 2020-09-26 22-46-38

Hey @t0xic0der, here is the screenshot of the modal you requested for. Check it out and let me know if any changes needed.

**Review by gridhead — CHANGES_REQUESTED** [review]
There are some changes I would like for you to make
- You would want to replace the `archive` icon in the overlay modal for something much appropriate. (Like a warning sign or an information sign - I would let you pick which one to go for)
- Also, you would want to make sure that the refresh button is aligned to center horizontally and has teal accent color. I would also appreciate if you replace the `tick` icon on the button for `sync` icon.
- The message does not need to be in title case. Simply convey "The API rate limit is exceeded from your IP address. Please try accessing the website later".

Good work done with the overlay modal. That would ensure that the users would not be able to do tasks when the API won't allow them to.

**Comment by s-katte** [comment]
Screenshot from 2020-09-27 00-36-46

@t0xic0der did all changes. Let me know if anymore.

**Review by gridhead — APPROVED** [review]

**Review by gridhead — APPROVED** [review]
Looks good to me. Merging.

Thank you for your contributions!

**Pull request merged**
